# panda_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100  # 控制循环频率（Hz）

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


# 7轴机械臂控制器配置
panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.02
      panda_joint1:
        trajectory: 0.1
        goal: 0.1

# 手爪控制器配置
panda_hand_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    mimic:
      - source_joint: panda_finger_joint1
        source_multiplier: 1.0
        offset: 0.0
      - source_joint: panda_finger_joint2
        source_multiplier: -1.0
        offset: 0.0
