panda_arm:
  planner_configs:
    RHPlanner:
      type: rh_planner_interface/RHPlannerManager
      max_velocity: 1.0
      max_acceleration: 2.0
      control_cycle_time: 0.001
    RecedingHorizon:
      type: rh_planner_interface/RHPlannerManager
      max_velocity: 1.5
      max_acceleration: 3.0
      control_cycle_time: 0.001

